### ISSUE TITLE
List of unfinished UI components

### ISSUE THREAD

**Issue by SecondFlight** [anthem-audio/Anthem#29]
Below is a list of atomic UI components that are either partially complete or not yet started. They are in no particular order.

- [x] Scrollbars
- [x] Knobs
- [ ] Sliders
- [ ] Accordion list (sidebar)
- [x] Color picker (no mockup exists yet) (#45)
- [ ] Piano control
- [x] Right click menu (#41)
- [x] Button groups (#22)

There are a lot that are not listed here, but most are part of a bigger system and ought to be built in that context.
